name: simple-todo-1

services:

  # アプリケーションサーバー
  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://app:temp-to-be-replaced@db:5432/simple-todo-1
    depends_on:
      - db

  # データベースサーバー
  db:
    image: postgres
    environment:
      # 管理者の設定
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  # データベース内を確認できるツール（開発用）
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080


