name: simple-todo-1

services:
  db:
    image: postgres
    # TODO: パスワードは環境変数で管理するよう変更
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: temp-to-be-replaced
      POSTGRES_DB: simple-todo-1 
    ports:
      - "5432:5432"

  # データベース内を確認できるツール（開発用）
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
