#!/bin/bash
set -e

# --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" 環境変数自体は公式イメージが自動で読み込むが、
# ユーザー名としては明示的に指定する必要がある
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" ON_ERROR_STOP=1 <<-EOSQL
  CREATE USER $DB_APP_USER WITH PASSWORD '$DB_APP_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $DB_APP_USER;
  \c $POSTGRES_DB
  GRANT ALL ON SCHEMA public TO $DB_APP_USER;
EOSQL
