name: CI

on:
  push:
    # 重要なブランチへのpush時に実行 
    branches:
      - master
  pull_request:
    # ブランチからのプルリクエストの作成・更新時に実行
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    # 事前実行 データベースをサイドカーとして起動
    services:
      postgres:
        image: postgres:15
        env:
          # DB作成時に利用される環境変数
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # DBの起動完了を待機
        options: >-
          --health-cmd "pg_isready -U postgres -d test_db" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      # 1. ソースコードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Deno のセットアップ
      - name: Use Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
        
      # ~~依存関係のインストール~~ Denoでは実行時に必要なモジュールを自動で取得するため不要

      # 3. コンパイルエラーのチェック
      - name: TS check
        run: deno check --frozen . # テスト含めすべてのファイル

      # 4. Lint の実行
      - name: Run lint
        run: deno lint

      # 5. テストの実行
      - name: Run tests
        env:
          # アプリケーションから接続する情報（テスト実行時は管理ユーザー）
          DB_HOST: localhost
          DB_NAME: test
          DB_PORT: 5432
          DB_APP_USER: postgres
          DB_APP_PASSWORD: password
        run: deno test -A --parallel --frozen
